### ISSUE TITLE
All/any other voting results through the remainder of 2021.


### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#111]
### Description
Originally created: 2023-12-28T12:36:52.874Z
https://www.patreon.com/FullFrontalFrog/posts?filters%5Btag%5D=poll
Due:

**Comment by FullFrontalFrog** [comment]
I've double and triple checked and we should have all 2021 polls accounted for in the following issues:

#110 / #119 / #133 / #134

Also, there were no _planned feature_ polls for 2022 or 2023, so we're done. Closed!
