### ISSUE TITLE
Stomp attack gets Joe stuck

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#12]
### Summary
In some rare and hard-replicated cases, Joe might get stuck in textures or even fall out of bounds in this specific spot in Treewish forest, closest elevator to entrance to Southeast Beach. 

### Consequences
Character gets stuck in textures 

### Steps to recreate
1. Go to closest elevator to entrance towards Southeast Beach
2. Go up
3. Jump off and buttstomp the ground
4- Repeat until this bug happens (optional)

This bug is hard to replicate and seem to happen in very few cases. It does happen in mentioned version as well, but it takes many tries to actually achieve this result.

**Result expected:** Joe lands on the ground like usually (is achieved in most cases) 
**Result achieved:** Joe gets stuck in textures and later falls out of bounds.

### Examples
See video [here](https://www.dropbox.com/s/5adodv10c0ifho6/Oh%20So%20Hero%202020-05-12%2009-09-48.mp4?dl=0)

### Configuration and system information
Wasn't provided by original reporter

**Comment by FullFrontalFrog** [comment]
I made a fix for this just before Pre Edition II was released. Please re-test.

**Comment by MagLjudik** [comment]
After retesting it several times today, I couldn't confirm this bug still exists. 🤔

**Comment by MagLjudik** [comment]
Didn't see this occur in 0.17.900
