### ISSUE TITLE
Daku AI issue

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#13]
### Summary
When Daku is on a platform above Joe, he keeps jumping up in order to grab Joe.

### Consequences
Daku keeps "attacking" until player moves to a spot without platform over him.

### Steps to recreate
1. Find a spot with platform over ground (Spaceship landing spot on Sheo Island Beach is one of these)
2. Stand under platform and watch Daku's Behavior. 

**Result expected:** Daku behaves like Joe isn't nearby 
**Result achieved:** Daku tries to grab Joe

### Examples
See video [here](https://www.dropbox.com/s/bpe4ddvqhok9snn/Oh%20So%20Hero%21%202020-11-28%2009-20-45.mp4?dl=0)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 10

**Comment by FullFrontalFrog** [comment]
@MagLjudik Thanks for the report. That video is a bit long. Got relevant timecodes?

**Comment by MagLjudik** [comment]
> @MagLjudik Thanks for the report. That video is a bit long. Got relevant timecodes?

Specifically the beginning of the video, on this box. Also, if you walk further under the wing, Daku in some cases would think you're still standing on that box and keep on jumping in order to grab Joe who isn't there. I can record another footage showing that, if needed.

**Comment by FullFrontalFrog** [comment]
Mag, this issue is pretty old. **When the next build (version 0.19.100) is complete** with the AI fixes I've been making lately, I would like you to see if this is still happening. Thanks!

**Comment by MagLjudik** [comment]
As of 0.19.100, this behaviour no longer happens. Daku behaves like Joe is not narby when Joe is on platform under Daku. Issue fixed.
