### ISSUE TITLE
Ajax gallery bug/crash

### ISSUE THREAD

**Issue by FullFrontalFrog** [FullFrontalFrog/OhSoHeroTracker#136]
Bunlord Ry reported:

There is a fatal crash. It's ONLY Ajax, and ONLY when you try to repeat the cum loop at the very end.
So in short. Set Loop to 'Single Scene Loop'. then head to the end of his scenes. It should crash.

**Comment by FullFrontalFrog** [comment]
Fix ready for 0.20.100!

**Comment by FullFrontalFrog** [comment]
@MagLjudik Please test this in 0.20.400!

**Comment by MagLjudik** [comment]
Fixed in 0.20.400
