### ISSUE TITLE
Koji-related issues in 0.20.002

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#139]
In 0.20.002, something happened to Koji

* When you do things with him in-game, after you're done, Koji disappears and Joe is soft-locked in the rhythm game.
* His interaction animation in gallery makes creepy noise until you go back to Animation 1, then it goes on as normal

**Comment by FullFrontalFrog** [comment]
Fix ready for 0.20.100! _(both issues)_

**Comment by MagLjudik** [comment]
Can confirm it's fixed in 0.20.100
