### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#14]
### Summary
When i press X to go foward after show the logo and a warning the game go to a black screen. Waited hours without any sight of life, restart game didn't help, neither reinstall

### Consequences
Can't play the game

### Configuration and system information
Windows (version not provided), used the 64-bit ZIP-file version

### Report
Reported by emintormorpher, 2020-09-06.

**Comment by FullFrontalFrog** [comment]
This was for an old version and we have no further information to go on. Naturally, we haven't been able to reproduce this, so I'm closing this ticket.
