### ISSUE TITLE
[Android] Options screen broken

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#142]
In android builds of version 0.20.300, Options screen is broken entirely, see attached screenshot.

![image](https://github.com/FullFrontalFrog/OhSoHeroTracker/assets/77382010/098211e7-f465-49e8-b488-313448df4cdb)

This bug doesn't seem to occur on Windows builds. On 0.20.200 android build it worked fine.

**Comment by FullFrontalFrog** [comment]
Fix ready for build v0.20.301 (forthcoming).

**Comment by FullFrontalFrog** [comment]
I've heard from the original bug finders this is fixed in v0.20.301, provided in the recent Patreon build post. Closed!
