### ISSUE TITLE
Touch controls remain on screen when exiting the game

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#145]
In 0.20.510 on Android, touch controls stay on screen after you exit the game back to title screen. This can be an issue when viewing the gallery.

![image](https://github.com/user-attachments/assets/2141089f-8c39-484f-9637-dcf107b98000)
![image](https://github.com/user-attachments/assets/82def3b3-2096-458d-a05f-b9e9674adf6f)
Pointed out by one of the members on our server.

**Comment by FullFrontalFrog** [comment]
I have a fix for this in the next build of the game tentatively versioned 0.20.700.

**Comment by MagLjudik** [comment]
Fixed as of 0.20.700
