### ISSUE TITLE
Stuck on the loading screen in Gallery

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#146]
In 0.20.600, I am no longer able to access gallery - it just spins indifinitely.

I tried this after beating Bates. Log provided
[Player.log](https://github.com/user-attachments/files/16874182/Player.log)

**Comment by FullFrontalFrog** [comment]
Fix ready for next build (0.20.601 or later).

**Comment by FullFrontalFrog** [comment]
Fixed.
