### ISSUE TITLE
Crash during sex with certain characters

### ISSUE THREAD

**Issue by FullFrontalFrog** [FullFrontalFrog/OhSoHeroTracker#148]
> Game is crashing when using SEX button moves on the guys with the bats and sometimes on other animations

[Player.log](https://github.com/user-attachments/files/17138549/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17138550/Player-prev.log)

This has not been widely reported, so the current priority is medium. However, every crash should be investigated as it's never a fun thing to happen when playing. Hopefully we can find a solution.

**Comment by FullFrontalFrog** [comment]
Only the first file, Player.log, is relevant; it's from v0.20.603. The Player-prev.log is from v0.16.100 which is years old.

Anyway, the system running the game has plenty of RAM, so it's not a memory issue. Here's the relevant portion of the error log:
```
UnityEngine.Texture2D:SetAllPixels32 (UnityEngine.Texture2D,UnityEngine.Color32[],int)
UnityEngine.Texture2D:SetPixels32 (UnityEngine.Color32[],int)
UnityEngine.Texture2D:SetPixels32 (UnityEngine.Color32[])
_0G.RasterAnimation:PopulateElanicTexture (int)
_0G.RasterAnimation:LoadTextures ()
_0G.GraphicController:SetAnimation (_0G.AnimationContext,_0G.RasterAnimation,_0G.GraphicController/AnimationEndHandler)
_0G.GraphicController:SetAnimation (_0G.AnimationContext,string,_0G.GraphicController/AnimationEndHandler)
OSH.OhSoGraphicController:StartSex (OSH.Sex)
OSH.Sex:Init (OSH.SexSetup,OSH.OhSoCharacter,OSH.OhSoCharacter,_0G.Attack,System.Action)
OSH.OhSoSexManager:Begin (UnityEngine.GameObject,OSH.SexType,OSH.OhSoCharacter,OSH.OhSoCharacter,_0G.Attack,System.Action,int)
OSH.SexableEnemy:OnPCInteract ()
OSH.Interactive:Update ()
```

What this tells me is that the player had sex with an enemy with the Lossless Animations set to Always, and the lossless animation (ElanicTexture) had an `Attempt to access invalid address` error.

I need to find a way to reproduce this issue so I can find a fix.

**Comment by FullFrontalFrog** [comment]
@MagLjudik When you have some time to do some retesting, please play through the game with **Lossless Animations set to Always** and have sex with various enemies and see if you encounter a crash. The original report says "the guys with the bats", which I assume refers to the Amarus, so try playing at least through Sheo Islands Beach and possibly Southeast Beach. Thank you!

**Comment by MagLjudik** [comment]
I played through many enemies, including Amarus and can't seem to get it to crash.

**Comment by FullFrontalFrog** [comment]
> I played through many enemies, including Amarus and can't seem to get it to crash.

Thanks for testing! I'm closing this as cannot replicate. Feel free to re-open if we get any new reports or evidence.
