### ISSUE TITLE
Game won't run

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#15]
### Summary
After having started the game and clicked "Start Game", nothing will happen. Background music and animation (waterfalls) keep playing but that's all. The game simply won't start.

I've tried all the different builds of the game, like ZIP file, 32-bit, 64-bit and so on, but sadly nothing changes :(

### Consequences
Game won't run

### Configuration and system information
Windows (version not provided), 32-bit ZIP-file game version

### Report
Reported by Christian on Patreon, 2020-09-02.

**Comment by FullFrontalFrog** [comment]
This was for an old version and we have no further information to go on. Naturally, we haven't been able to reproduce this, so I'm closing this ticket.
