### ISSUE TITLE
[v0.20.700] Bates Game Over Animations have improper letterboxing

### ISSUE THREAD

**Issue by FullFrontalFrog** [FullFrontalFrog/OhSoHeroTracker#154]
Bates Game Over Animations do not have proper letterboxing on some display resolutions. This makes it look like the animation is cut off at the top and the bottom as the background shows through. Really it just needs to be properly formatted like the other game over animations.

**Comment by FullFrontalFrog** [comment]
I had to move some objects around in the Game Over Screen and also add a new blank background image for a properly aspect ratio'ed background color (pink). Fix ready for v0.20.800!

**Comment by MagLjudik** [comment]
Fixed as of 0.20.800
