### ISSUE TITLE
[v0.20.701] Unable to pick sex in dialogue with Ket at Southeast Beach

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#156]
**Buggy dialogue with Ket on Southeast beach**

See videos in T0156 on Dropbox, courtesy of Ahzi from our community.

The bubble seems to stay during the selection of dialogue. Does not seem to affect gameplay though.

(UPDATE: Gameplay is affected. See comments.)

**Comment by FullFrontalFrog** [comment]
Image attachment provided by StarryTheTanuki
![image](https://github.com/user-attachments/assets/cdf16254-2cac-4c8c-a62f-22df822dc28c)

**Comment by FullFrontalFrog** [comment]
StarryTheTanuki says he's unable to select the second option, but @MagLjudik you said this does not seem to affect gameplay. Can you please confirm if the second option is select-able?

**Comment by MagLjudik** [comment]
I will recheck it with a fresh save ASAP. But according to one of the videos, it’s still possible to choose the second, but only the first time Joe talks to Ket in that location.

**Comment by FullFrontalFrog** [comment]
> I will recheck it with a fresh save ASAP. But according to one of the videos, it’s still possible to choose the second, but only the first time Joe talks to Ket in that location.

Thanks for checking! What happens when you leave the area and return? Can you select it then?

**Comment by MagLjudik** [comment]
> Thanks for checking! What happens when you leave the area and return? Can you select it then?

So, this is how it seems to be:

When you open dialogue with Ket In SEB on the first time, it works. But any time after the first, you won't be able to select the second option - and thus will not be able to unlock the animation with Ket. 

You can only unlock it if you select it on the first time you speak with Ket there. Any time after, the second option is not selectable. This is not fixable by re-entering the area, relaunching the game or any other means. Might it have something to do with dialogue condition for the character?

The reason why I thought it does not affect the gameplay was because I thought it only happens if you already have that animation unlocked, but apparently not. I added my recording on a fresh save to demonstrate how it is for me.

**Comment by FullFrontalFrog** [comment]
> > Thanks for checking! What happens when you leave the area and return? Can you select it then?
> 
> So, this is how it seems to be:
> 
> When you open dialogue with Ket In SEB on the first time, it works. But any time after the first, you won't be able to select the second option - and thus will not be able to unlock the animation with Ket.
> 
> You can only unlock it if you select it on the first time you speak with Ket there. Any time after, the second option is not selectable. This is not fixable by re-entering the area, relaunching the game or any other means. Might it have something to do with dialogue condition for the character?
> 
> The reason why I thought it does not affect the gameplay was because I thought it only happens if you already have that animation unlocked, but apparently not. I added my recording on a fresh save to demonstrate how it is for me.

Thank you for clarifying!

For, the time being, if anyone wants to see Ket's animation accessible through the second option, they can use the cheat in the gallery listed here:
https://wiki.ohsohero.com/gallery#cheat_code

I'll have this fixed next build!

**Comment by FullFrontalFrog** [comment]
I got a fix ready for next build! (v0.20.800 or later.) Gonna be working on more bug fixes in the meantime.

**Comment by MagLjudik** [comment]
Fixed in 0.20.800
