### ISSUE TITLE
Linux build won't start

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#18]
### Summary
Player can't get past the patron screen, neither controller nor keyboard works.  tried with controllers plugged in and tried it without controllers, no fancy mice or anything else plugged in, the keyboard/controller works on the first screen, just not this one.

Problem seems to occur only on current version, previous builds seemed to work perfectly fine.

### Consequences
Player is not able to play newest version of the game

### Steps to recreate
1. Install and launch the game

**Result expected: all intro screens are clicked through** 
**Result achieved: Game does not load past patron screen**

### Examples
Not applicable 

### Configuration and system information
Linux Build, Opensuse Tumbleweed/Gnome, hardware: Intel Core i7 - 4790 - GeForce GTX950

**Comment by MagLjudik** [comment]
I'll try to replicate the bug once I set up a separate machine with 2-3 popular linux distros running on it.

**Comment by MagLjudik** [comment]
Same issue was reported by another Linux build player.

Config:
Manjaro Plasma on a laptop with an i7-1165G7

Log file was provided:
[Bilb_Player.log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/5909645/Bilb_Player.log)
Crash issue in it says following:

`SystemNotInitializedException: [FMOD] Initialization failed : FMOD.Studio.System.create : ERR_HEADER_MISMATCH : There is a version mismatch between the FMOD header and either the FMOD Studio library or the FMOD Low Level library.
`

**Comment by FullFrontalFrog** [comment]
@MagLjudik Didn't you say in one of the Discord channels you were able to replicate it?

**Comment by MagLjudik** [comment]
> @MagLjudik Didn't you say in one of the Discord channels you were able to replicate it?

I couldn't replicate it because I didn't have a working linux machine at that moment. I mentioned that I'll try to replicate it once I have a linux machine set up. 

But someone of us did mention that it's likely that it was caused by FMOD or Unity upgrade?

**Comment by FullFrontalFrog** [comment]
You did! A few comments ago. =}

Yes, I will probably have to upgrade FMOD.

**Comment by MagLjudik** [comment]
Linux players report that v. 0.16.110 starts up and runs just fine. Issue can be closed.

**Comment by FullFrontalFrog** [comment]
@MagLjudik Thanks for testing this and the other bugs as well!
