### ISSUE TITLE
Camera stuck in Brask's Jungle under specific conditions

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#19]
### Summary
At Brask's Jungle, when coming from Brask's Palace, when player slid to the left and got hit by Goliath, camera got stuck at the position on screenshot. Player was able to fix it by pressing Esc. 

Bug seems to not be easy to replicate.
### Consequences
Camera gets stuck at one position until player presses esc or pause button. 

### Steps to recreate
1. Go to Brask's Jungle via Brask's Palace or Forbidden Bayou.
2. When near the gate that is activated by crystals, slide (?)

**Result expected: camera switches over to section with Goliath** 
**Result achieved: camera is stuck**

### Examples
![image](https://user-images.githubusercontent.com/77382010/106439376-e624f680-6477-11eb-89d8-240d561c0509.png)
_Position it was stuck at_

### Configuration and system information
Wasn't provided

**Comment by FullFrontalFrog** [comment]
My camera room system is not perfect. It can be better. Maybe I should leverage Gate or something similar that maintains a single instance (singleton) based on rules.

**Comment by FullFrontalFrog** [comment]
The camera code has changed a lot since this was reported. Please give this a retest in 0.19.300!

**Comment by MagLjudik** [comment]
The issue is fixed
