### ISSUE TITLE
Specific goliath animation 

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#21]
### Summary
When Goliath downed and Joe starts interaction, seem like this specific point in the animation looks somewhat blurry. (Reporter pointed to that square on the eye)

### Consequences
None for the gameplay

### Steps to recreate
1. Find and down the Goliath
2. Start interaction and look at animation

### Examples
![image](https://user-images.githubusercontent.com/77382010/106441289-284f3780-647a-11eb-9959-329c4feb5692.png)

### Configuration and system information
Was not provided

**Comment by FullFrontalFrog** [comment]
This is likely a result of built-in compression settings. Not sure if I can provide a simple fix for this without impacting performance, but I will try.

**Comment by FullFrontalFrog** [comment]
I'll be addressing this through a new form of compression. I got other tickets for that and will revisit this issue later.

**Comment by FullFrontalFrog** [comment]
This should be fixed when using **High Quality Animations in v0.16.200**. I have no plans to address this for standard quality.

**Comment by MagLjudik** [comment]
Fixed a while ago. As of 0.16.500 in HQ mode there's no such bug.
