### ISSUE TITLE
Cannot launch the game

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#22]
### Summary
A user has reported to me through the mail that they cannot start the game and attached two log files. 
[Player.log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/5967714/Player.log)
[Player-prev.log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/5967715/Player-prev.log)

Most likely is client-side issue once again.

**Comment by FullFrontalFrog** [comment]
Did a Martian send this in?

```
TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.
  at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) [0x00000] in <00000000000000000000000000000000>:0 
  at System.TimeZoneInfo.get_Local () [0x00000] in <00000000000000000000000000000000>:0 
```

This was called by FMOD, BTW.

**Comment by MagLjudik** [comment]
> Did a Martian send this in?

I don't know how this is even possible, maybe their system is corrupted or something.

Anyway, I responded to their mail with some generic stuff to try (different builds from our itch io, system cleanup etc.)
I'll report here if I get an answer or not. If I get no answer within 7 days, this issue can be closed.

**Comment by MagLjudik** [comment]
I didn't get any response from them, so we can't go on with this issue without any further information.
