### ISSUE TITLE
"Press X" issue (Mashout Hold Meter)

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#23]
### Summary
Apparently, that specific spot does not update control buttons/graphics with different input devices and always shows the keyboard control (Press X). It's especially confusing if one's using PS4/PS5 controller, where struggling is actually bound to square and not cross.
See screenshot.

### Consequences
If player uses dualshock 4, that might confuse them at first.

### Steps to recreate
1. Get banged by any enemy in the game

**Result expected: "Press square"** 
**Result achieved: "Press X"**

### Examples
![image](https://user-images.githubusercontent.com/77382010/109780986-cf54f980-7c07-11eb-9bd4-429201952f59.png)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 10

**Comment by FullFrontalFrog** [comment]
A fix is ready for 0.16.200.

**Comment by MagLjudik** [comment]
I can confirm that this issue was fixed in v0.16.200
