### ISSUE TITLE
"Stuck" in a small area in Brask Jungle

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#24]
### Summary
In Brask Jungle, Joe can get "kind of" stuck on that spot screenshot shows. It's possible to get there through sliding, but kinda hard to get out of there.

### Consequences
Players can feel "stuck", even tho it's possible (but hard) to get out of there without restarting the level.

### Steps to recreate
1. Enter Brask Jungle
2. Look for area on screenshot

**Result expected:** You can get in and get out, or neither. 
**Result achieved:** You can get in but hardly get out.

### Examples
![image](https://user-images.githubusercontent.com/77382010/109784271-31632e00-7c0b-11eb-9b08-d7bf19c64f46.png)

### Configuration and system information
Not provided by original reporter.

**Comment by FullFrontalFrog** [comment]
A fix is ready for 0.16.200.

**Comment by MagLjudik** [comment]
I can confirm that issue was fixed in v0.16.200
