### ISSUE TITLE
Unusual RAM consumption

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#25]
### Summary
One of the players has reported significant performance drop in the game due to high RAM consumption. I went to investigate this and found out that memory consumption is increased the longer you are present on the same level. Switching to another level sets consumption back somewhat, but the same things happen again.

I did a 5-minute observation on 3 different levels and seemingly, Southeast beach is the worst, going up from 400 MB to almost 9 GB RAM consumption over 5 minutes. Other levels seem to have the same problem, but with less memory consumption.

Problem seems to occur on this newest build, while Pre Edition II has no such issue.

### Steps to recreate
1. Launch the latest build of the game and start
2. Start task manager over the game or on another screen
3. See RAM consumption grow over time.

**Result expected:** No large RAM consumption, like in PE II 
**Result achieved:** RAM usage is increasing the more time you spend in the game. 

### Examples
See [here](https://www.dropbox.com/s/0qhk2noycs10r3u/T0024_mov_Output_1.mp4?dl=0)*
*Note: My OS is on Russian, so in order to understand the values, note that column 1 is CPU, column 2 is RAM. 

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 10

**Comment by FullFrontalFrog** [comment]
I'm trying to think if there's anything we changed recently that would cause this and I have a theory. It could actually be something I already fixed.

Specifically, there was some experimental work I was doing with the GraphicController where it would generate a new texture and not dispose of it. I've since changed this.

I recommend re-testing this on the next build, 0.16.200.

**Comment by MagLjudik** [comment]
I did the same test on the build 0.16.200 and can confirm that performance issues has disappeared. RAM consumption is at between 300-600 MB, depending on the level, CPU and GPU usage are between 10% and 20%. So the issue can be closed. I will open a new one in case there's any new performance issues reported.
