### ISSUE TITLE
"Invisible Wall" For Daku?

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#27]
### Summary
In the very beginning of the game, somehow, first Daku cannot get past a specific spot near Ket's first appearance. See video in "Examples"

### Consequences
No overall effect on the game, but might look weird.

### Steps to recreate
1. Start the game on Sheo Island Beach, at beginning of the level.
2. Go towards the first Daku and lure him to follow you.
3. Go back towards "first Ket" and see the result

**Result expected:** Daku follows all the way 
**Result achieved:** Daku gets stuck behind "invisible wall" until you go back to him.

### Examples
See vid [here](https://www.dropbox.com/s/xm2x5l5trlo6g02/Oh%20So%20Hero%21%202021-03-24%2022-05-31.mp4?dl=0)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 10

**Comment by MagLjudik** [comment]
Turns out it's a feature preventing enemies from getting to spots where they might get stuck. Probably not necessary to keep this report, unless re-make it into an AI-related issue

**Comment by FullFrontalFrog** [comment]
Not the best design but it's what we got until we have time to invent and implement a better solution (e.g. wall-aware AI).
