### ISSUE TITLE
No refilling of HP and SP when Signal is swooned

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#28]
### Summary
Sanmer from OSH discord has reported that when you "do the refill" with Signal, it doesn't give you any HP or SP, unlike with other enemies. I've investigated this and can confirm it is an existing issue.

### Consequences
Signal can't be used to refill HP and SP. 

### Steps to recreate
1. Go to Lood City
2. Make Signal horny
3. "do the refill" 
4. Check the stats

**Result expected:** HP and SP slightly recovered 
**Result achieved:** HP and SP are the same as before

### Examples
[Here](https://www.dropbox.com/s/wixc2nkxnybntar/Oh%20So%20Hero%21%202021-04-15%2008-44-48.mp4?dl=0)

### Configuration and system information
Not provided by original reporter

**Comment by FullFrontalFrog** [comment]
Thanks for the report! I have a fix ready for next build (0.16.300).

**Comment by MagLjudik** [comment]
I can confirm that this bug was fixed in v0.16.300
