### ISSUE TITLE
File corruption

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#3]
### Summary
Loading/saving state in Treewish forest might cause game to freak out and start glitching.

### Consequences
Game might start behaving unpredictably, making it hard or impossible to play. Save files might get corrupted and prevent players from progressing further in the game.

### Steps to recreate
*I currently am trying to reproduce the bug, so information might get updated.
1. Launch the game
2. Choose empty save state
3. Repeatedly push start to skip intro.
4. As game starts, jump and press pause
4.5 Alternately, jump up the ball and press pause

Result expected: Normal gameplay
Result achieved: Multiple glitches and weird behavior

### Examples
**1. Something happens when going to Treewish forest... load sequence freakout?**
See video [here](https://cloud.magolor.icu/s/wW7kqdmG5yZrewq)

**2. Game gets broken by loading/exiting save states and pushing buttons**
See video [here](https://cloud.magolor.icu/s/orNHCGd3H593KZx)

### Configuration and system information
Wasn't provided by original reporter

**Comment by FullFrontalFrog** [comment]
This was reported on Pre Edition II by DevSkaRued on Discord.

**Comment by FullFrontalFrog** [comment]
Sorry, it has been a while. @MagLjudik Please see if this is still an issue. Thanks!

**Comment by MagLjudik** [comment]
I repeated the steps in description and everything seems fine, no glitches or freakouts.
