### ISSUE TITLE
Wrong Ket animation on Sheo Islands Beach

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#30]
### Summary
During new build test routine, I found that Ket's sprite on Sheo Island Beach has been replaced by Ket's sprite from Southeast Beach. 

Ket on Southeast Beach is not affected by any bugs.

### Consequences
It looks out of place, but has no other effects on the game

### Steps to recreate
1. Start new game or load save
2. Go to Sheo Island Beach and find Ket

**Result expected:** Animation of Ket sitting on the chair (like in 0.16.200) 
**Result achieved:** Animation of Ket enjoying the ice pop while "standing" on the chair.

### Examples
![image](https://user-images.githubusercontent.com/77382010/116773990-95627100-aa59-11eb-9330-2a39d758c63c.png)
![image](https://user-images.githubusercontent.com/77382010/116774004-a01d0600-aa59-11eb-8eb4-842570094f55.png)
![image](https://user-images.githubusercontent.com/77382010/116774013-b0cd7c00-aa59-11eb-8380-7e99fa330243.png)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 10

**Comment by FullFrontalFrog** [comment]
Thanks for reporting this! I determined the cause of the issue and a fix has been made for v0.16.400.

**Comment by MagLjudik** [comment]
Issue fixed in 0.16.400.
