### ISSUE TITLE
Clip through container wall on Southeast Beach

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#31]
### Summary
Joe can clip through the container wall near Cas' Shack

This bug is specific to that spot and not universal, like one in Pre Edition II.

### Consequences
Player can enter out of bounds at this spot and might not be able to retrun again.

### Steps to recreate
1. Go to the Cas' Shack
2. There's a container wall next to it. Jump and try to "land" on one container
3. Then use slide to clip-through.

**Result expected:** Joe can't get past containers
**Result achieved:** Joe clips through containers and out of bounds.

### Examples
[T0031](https://www.dropbox.com/s/2pf9m58t66o0jkb/Oh%20So%20Hero%21%202021-05-01%2009-02-30.mp4?dl=0)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 10

**Comment by MagLjudik** [comment]
(Going further, if examples will contain "hot material", I will provide the issue folder name instead of direct link for additional safety)

**Comment by FullFrontalFrog** [comment]
This area will be redesigned later anyway, so this is low priority.

**Comment by FullFrontalFrog** [comment]
Possible fix ready for 0.17.000

**Comment by MagLjudik** [comment]
I tested and it seems to work, I can no longer get through containers.

**Comment by MagLjudik** [comment]
Been fixed long time ago.
