### ISSUE TITLE
Camera changes too suddenly on Southeast Beach

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#32]
### Summary
At one specific spot on Southeast Beach, camera seems to be shifting by instantly changing the scope, without animation or anything. Joe is suddenly in the center/edge of the frame. (See example)

Not sure if it's a bug, but posting just in case.

### Consequences
Players might be slightly confused where to shift their sight. 

### Steps to recreate
1. Go to the Southeast beach
2. Get to the section with moving crane

**Result expected:** Smooth camera movement
**Result achieved:** Camera changes the scope all of a sudden without any smoothness

### Examples
[T0032](https://www.dropbox.com/s/0bwwpwsm3n08noh/Oh%20So%20Hero%21%202021-05-01%2009-19-56.mp4?dl=0)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 10

**Comment by FullFrontalFrog** [comment]
Thanks~ I've discovered the root of the problem. It was related to my recent camera code change, so this issue may exist elsewhere in the game as well. In any case, I've made a fix. It's ready for 0.16.400.

**Comment by MagLjudik** [comment]
Fixed in 0.16.400
