### ISSUE TITLE
Not playing "first sound" on some animations

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#34]
### Summary
Certain animations don't play their first SFX both in gallery and game, even tho on second iteration in gallery, the sound plays fine. 
Simply, it means that SFX is implemented but is not playing. Here are the animations where I found this issue:
Enemies: Stier №3, №4. №5 and Gatis №6
NPCs: Lemiel, Griff, Domino, Tiburon and Jack.

### Consequences
None gameplay-wise.

### Steps to recreate
1. Go to Gallery Mode (turn off music to better hear what I mean)
2. Choose any of the abovementioned animations.
3. Or go to Lood City and swoon Stier to test it in-game. 

**Result expected:** SFX playing correctly on first attempt
**Result achieved:** SFX does not play, neither in gallery (not on first iteration) nor in game

### Examples
Folder T0034

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 10

**Comment by MagLjudik** [comment]
I added a label for Music & SFX bugs in case people will report similar things in the future

**Comment by FullFrontalFrog** [comment]
Thanks, Mag!

**Comment by MagLjudik** [comment]
Issue seem to have disappeared in 0.16.400. Closing for now.
