### ISSUE TITLE
Unusually high memory consumption for certain players

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#36]
### Summary
Some players have reported a very high memory consumption for Oh So Hero, for both version 0.16.400 and .500. While I was unable to find out the cause on my own and it wasn't reported by very many users, this might indicate there's either memory leak or a bug triggered in specific scenarios. The issue seems to be platform-independent. 

### Examples
User 1, Linux and Windows, v0.16.400
![image](https://user-images.githubusercontent.com/77382010/124164442-ee25a880-daa0-11eb-9883-4f21569c17bf.png)
![image](https://user-images.githubusercontent.com/77382010/124164451-f1b92f80-daa0-11eb-9783-baeff58c73be.png)

User 2, Windows, v0.16.500
![image](https://user-images.githubusercontent.com/77382010/124164542-11e8ee80-daa1-11eb-9dd6-2fa7780f6e47.png)

**Comment by FullFrontalFrog** [comment]
Thanks for the help, Mag! I'm sure there is something here that needs fixing. I just need to dig in deeper. Ribbit~

**Comment by MagLjudik** [comment]
Here's some notes from my observations during test runs of the latest version

* The RAM consumption starts around 500 Mb and grows as player triggers more different animations. RAM usage is reset once player switches location. Locations also affect RAM consumption somewhat, but not too significantly.
 
* The GPU Memory (further named as VRAM) starts at 3.3GB in base on fastest settings, yet switching settings to Fantastic increases usage with 200-300MB, so not a significant change. Locations do also affect VRAM usage, yet insignificantly. 

* On integrated GPUs and also on normal ones, where all VRAM is used up, the system turns to RAM for more memory, thus increasing the RAM consumption heavily. One of the users who struggled with lags mentioned they had a GTX1060 with 3GB VRAM. Which means, 3GB VRAM on a non-integrated GPU is a bare minimum to play the game smoothly.

* There's no other way I could increase VRAM and RAM consumption but setting HQ animations to "always".  When done that, VRAM consumption grown up to 6 GB in some locations.

* I'm not sure about this one, but VRAM consumption didn't reset between locations, like RAM did, while using HQ everywhere. Maybe I should test this further to make sure it wasn't a coincidence.

**Comment by FullFrontalFrog** [comment]
I have a couple bits of news to report.

First, an issue I just fixed:
Current work may improve RAM usage, but main difference is that high quality animations set to always will now load all animations into RAM upon entering an area rather than loading on demand. What this means is the loading time and RAM will increase upon entering the area, but there will be no loading stutters when viewing sex animations, nor will RAM usage climb over the course of the stage.

Second, another issue I confirmed to exist regardless of the first issue:
OSH has a small memory leak. Tested on Win 64. Load a game saved in Lood City, return to title, repeat. Notice RAM usage slowly climbs over time. I I'll need to address this.

**Comment by FullFrontalFrog** [comment]
@MagLjudik How do you check for VRAM usage? I use the Windows Task Manager to look at RAM usage but not sure what that all includes.

**Comment by MagLjudik** [comment]
@FullFrontalFrog Thanks for the hard work 👍 

1. I think the solution with loading directly is good and will make the gameplay more comfortable for people with powerful rigs. 

2. I tested this and it is indeed happening, even if very insignificantly increasing the RAM, it might be an issue on weaker machines. 

3. Unfortunately, Windows' built-in task manager does not display VRAM usage for whatever reason. However, you can either use Xbox game bar (default Win + G, if you haven't deactivated it) for monitoring the VRAM usage or use a third-party overlay like FPS Monitor. 

![image](https://user-images.githubusercontent.com/77382010/126451700-2f12c494-21b2-465d-bd46-956400ca6254.png)

**Comment by FullFrontalFrog** [comment]
Thanks for the help! @MagLjudik

**Comment by MagLjudik** [comment]
Notes from observations during test run of v0.16.600

* RAM consumption has somewhat decreased from ~500MB to ~370-400MB in base with HQ turned off.

* VRAM usage has decreased from 3.3 GB to around 1.9 GB on non-HQ animations and fantastic settings.  which is also slightly less than in previous build. However, as I noticed, the readings are not 100% trustworthy, because both Game Bar and FPS Monitor show VRAM consumption for the whole system rather than single task. Furthermore, I'm using a QHD-display (2K resolution) and on FullHD it might consume less. VRAM consumption also depends on amount of characters/animations on the level, difference especially noticed in HQ mode set to Always.

**Comment by FullFrontalFrog** [comment]
Sounds like a step in the right direction. Thanks for the analysis, @MagLjudik!

**Comment by MagLjudik** [comment]
Notes from observations during test run of v0.17.900

RAM consumption is around 400-500MB in most locations, CPU usage is between 5%-15%, depending on location and amount of enemies around. No preloading is used.

As for VRAM, it's stable at 3GB for me. Do note, however, that since I run insider builds of Windows 11, that can mean performance issues caused by system itself, so on stable builds it might run much better.

**Comment by FullFrontalFrog** [comment]
Thanks for the report, Mag! I think the main issue is fixed, but there's useful info in this issue and there may still be ways for me to improve performance. Gonna keep this open at low priority to review again at a future time.

**Comment by FullFrontalFrog** [comment]
Let's do one more retest in 0.20.002 or 0.20.100. If there's nothing alarming, I'm gonna close this issue.

**Comment by MagLjudik** [comment]
I made a quick run and on everything at max + preloading, fRAM consumption is around 6-7 GB (Depending on location). Without preloading, it's around 1.2 GB (or around 600 MB if HQ is turned off). 

To me, it all looks alright. My recommendation to the users would be to turn off preloading if they have low RAM amount or have an integrated GPU, which uses RAM as memory, usually up to 2-3 GB. 

Issue can be closed for now.
