### ISSUE TITLE
Clip through at Brask Palace's hidden area

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#37]
### Summary
The bug is similar to #31 except it's located in Brask's palace, near the hidden character.

### Consequences
Player can enter out of bounds at hidden spot in Brask's palace and falls out of bounds.

### Steps to recreate
1. Go to Brask's palace
2. Find hidden character
3. Slide into the wall

**Result expected:** Joe can't get past wall
**Result achieved:** Joe clips through wall and out of bounds.

### Examples
![image](https://user-images.githubusercontent.com/77382010/130905646-b71e2d08-6631-4b68-9ea7-9baab85ca834.png)

**Comment by FullFrontalFrog** [comment]
Unable to reproduce in 0.17.000.

**Comment by MagLjudik** [comment]
Couldn't replicate on 0.17.000 as well. I could get into the state of "stuttering", when Joe is trying to get into the wall and he gets pushed back out by the game. Though I couldn't get out of bounds.

**Comment by MagLjudik** [comment]
Fixed
