### ISSUE TITLE
Camera switch issues in Treewish forest

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#38]
### Summary
This bug has happened before. In specific spots, when joe jumps and hits his head, camera will be stuck on a new location, until camera update happens.

### Consequences
Players lose track of Joe.

### Steps to recreate
1. Go to spots shown in video examples
2. Jump using the spring and hit Joe's head on platform above
3. Bug usually happens after 2 attempts.

**Result expected: Camera switches position along with Joe** 
**Result achieved: Camera remains at wrong area**

### Examples
T0038 at Dropbox

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 11

**Comment by FullFrontalFrog** [comment]
I believe this has been fixed with my recent camera work. The room focus is now based on where Joe is standing (his feet, rather than his head). Please retest in 0.19.300!

**Comment by MagLjudik** [comment]
Issue fixed
