### ISSUE TITLE
Bax turns into gray box under specific conditions

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#39]
### Summary
Several users have reported that, upon entering the new area (the Dojo) for the first time, when hitting first Bax on location, he suddenly turns into gray square. I couldn't replicate this bug, but reports suggests that it happens only on the first time entering the Dojo. Whether it's overall first time or first time per game launch is not clear yet

### Consequences
None for the gameplay, but might ruin the atmosphere

### Steps to recreate
1. Enter the Dojo
2. Go to the first Bax on location and hit him

**Result expected:** Nothing out of ordinary
**Result achieved:** Gray square covers the sprite

### Examples
![image](https://user-images.githubusercontent.com/77382010/131716294-20207b4b-2e79-4bb8-bec0-ed0658b78d72.png)

### Configuration and system information
Wasn't provided by original reporter(s)

**Comment by FullFrontalFrog** [comment]
Thanks for the report! I was able to reproduce this with High Quality Animations set to Always. There should be a simple fix for this; just need to find it.

**Comment by FullFrontalFrog** [comment]
I fixed it. Just had to delete the Bax_HitStunned_ElanicData.asset then rebuild bundles to regenerate it properly.

**Comment by MagLjudik** [comment]
Seems to be fixed
