### ISSUE TITLE
Ultrawide screen issues

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#44]
### Summary
Several users have pointed out issues when playing with ultrawide screen. That only affects main menu and option menu, with some overlaps and cutoffs with no ability to scroll option menus.

As I don't have suitable screen for testing, I couldn't replicate the issue, but screenshots provided by one of the users work as proof of the bug's existence.

### Consequences
Users with ultrawide screens can't use options menu properly unless changed resolution with aspect ratio 16:9. 

### Steps to recreate
1. Launch the game on an ultra-wide screen
2. Go to options

**Result expected:** Options fit on screen or scrolling 
**Result achieved:** Options cut off

### Examples
![image](https://user-images.githubusercontent.com/77382010/137350926-a03aa6e2-6c27-45db-8406-e1508246a6c2.png)
![image](https://user-images.githubusercontent.com/77382010/137350949-a511c4b5-1274-4aae-951d-34365066fe4e.png)

### Error Log
Not provided

### Configuration and system information
Screen resolution: 3440x1440. No other info provided.

**Comment by FullFrontalFrog** [comment]
Thanks for the report, Mag! This will need to be tackled with further UI work.

**Comment by FullFrontalFrog** [comment]
I have a fix ready for v0.17.300!

**Comment by MagLjudik** [comment]
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/77382010/209113944-ece4534c-6b86-4b9d-b967-4a0f4248eac4.png">
Now that I have an Ultrawide screen myself, I noticed that new Pause menu is a bit buggy on this resolution, so I'm reopening this issue.
@FullFrontalFrog can you investigate when you have extra time? :)

**Comment by FullFrontalFrog** [comment]
I will fix this in a future update with full-game support for ultrawide monitors. Until then, in the Options, please select a resolution using a 16:9 aspect ratio, such as **1920x1080** or **3840x2160**.

**Comment by MagLjudik** [comment]
This seem to affect some other places as well, like intro: 
![image](https://user-images.githubusercontent.com/77382010/230659542-4fd0221b-3641-43fb-ad32-ee0c7b9ed51e.png)
This UI does not display when dialog box is up and is partially hidden behind the picture. I tested it in classic 16:9 resolution and it does not happen there, so it seem to be a resolution-specific bug.

**Comment by MagLjudik** [comment]
Camera stutters in Hiroto Dojo near first Haya on ultrawide res (for the record)

**Comment by FullFrontalFrog** [comment]
I'm taking care of this as part of Android. Please retest next build or by v0.20!

**Comment by FullFrontalFrog** [comment]
@MagLjudik Let me know if you think this is fixed!

EDIT: There are multiple issues here reported in the comments, so please check everything. Thanks!

**Comment by MagLjudik** [comment]
@FullFrontalFrog The UX on both Android and Windows builds look correct. Camera issues still present on Windows ultrawide res, but they're not gamebreaking.

**Comment by FullFrontalFrog** [comment]
> @FullFrontalFrog The UX on both Android and Windows builds look correct. Camera issues still present on Windows ultrawide res, but they're not gamebreaking.

OK, thanks for checking, Mag! All the UI/UX stuff has been resolved it seems, so let's consider this issue closed.

If there are any ultrawide camera issues that are egregious or make gameplay awkward, they can be submitted as a separate issue (or multiple issues), because they are likely the result of LevelRoom/CameraRoom code.
