### ISSUE TITLE
Dualsense controllers not compatible with the game

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#45]
### Summary
Users have reported that Playstation 5 controller, aka DualSense is not working with Oh So Hero. This issue does not affect other Playstation controllers like Dualshock 4. Updating Rewired might solve this issue, as latest version [supports DualSense](https://guavaman.com/projects/rewired/docs/SupportedControllers.html).

### Consequences
Players cannot use DualSense controllers to play Oh So Hero

### Steps to recreate
Not applicable

### Examples
Not applicable

### Error Log
Not applicable

### Configuration and system information
Was not provided

**Comment by FullFrontalFrog** [comment]
Can't address this one until I obtain the hardware. Lower priority. What even is a PS5? j/k

**Comment by FullFrontalFrog** [comment]
I updated Rewired. Still don't have a PS5 controller to test this, but in theory it should work now. Let's check after next release: v0.18.400.

**Comment by FullFrontalFrog** [comment]
I tested a PS5 controller and it works. Closed.
