### ISSUE TITLE
Title/menu related bugs

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#46]
Updated to be displayed as raw code, for easier copy-pasting.

### Summary
As reported by one of the users, game keeps freezing when going back to title. The gallery is broken as well

### Consequences
Player is unable to access part of the game content.

### Steps to recreate
Couldn't repeat

### Error Log
[Player-prev (1).log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/8454385/Player-prev.1.log)
[Player (1).log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/8454386/Player.1.log)

### Configuration and system information
Laptop,  Intel(R) Pentium(R) N3710  @ 1.60GHz, 4GB Ram, built-in GPU.

**Comment by MagLjudik** [comment]
User reports that the bug was resolved by updating the game? Apparently they used older version than one reported in the bug. 

Issue closed

**Comment by FullFrontalFrog** [comment]
Thanks for following up on this and closing as needed. Always good to have a record even if it's nothing that needs to be fixed. =}
