### ISSUE TITLE
Dialog completion spreads across saves 

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#47]
### Summary
When player is starting a game in a new save slot after they played in another save with progress in dialogs, game in new save slot acts like Joe has already talked with same characters. 

This bug only occurs if player started new game in empty slot without restarting Oh So Hero first. If player starts fresh slot right after booting up the game, the bug does not happen.

### Consequences
This bug can lead to, e.g. inability to get map from Ket at the start, as new game thinks that Joe already talked to Ket. Further bugs might be on place as well. 

### Steps to recreate
1. Launch Oh So Hero
2. Play through first level on save slot with in-game progress past this level. Make sure that you already talked with Ket on every appearance in this game.
3. Exit to title screen, but **do not exit the game**
4. Start a new game in an empty slot and attempt to get a map from Ket. 

**Result expected: Fresh game = no progress** 
**Result achieved: Even fresh game has some unwanted progress**

### Examples
See T0047 on Oh So Issues Dropbox

### Error Log
[Player.log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/9192686/Player.log)
[Player-prev.log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/9192687/Player-prev.log)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 11

**Comment by FullFrontalFrog** [comment]
I would imagine it not as spreading across saves, but rather as being retained in memory and not-reinitialized on a new game. TBD!

**Comment by FullFrontalFrog** [comment]
Possible fix ready for v0.18.400!

**Comment by MagLjudik** [comment]
Fixed in 0.18.500
