### ISSUE TITLE
Gallery fails for players with custom key binds

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#48]
### Summary
Some players have reported that, when they rebind keys, Gallery stops working. Ket managed to replicate this bug and come to conclusion that this is because "play climax" key is null, which happens when players rebind default "S" key. Other gallery-related keys are worth checking as well.

The bug happens because players are unable to bind the same key to more than one action overall, even tho by default there's double or triple keybinds, I'll create a separate bug report about it.

This error is fixed by resetting keybinds to default or binding new keys for the gallery.

### Consequences
Players are unable to access the gallery. Game freezes and requires alt+f4 to exit.

### Steps to recreate
1. This tutorial is for the keyboard with default keymapping. Make sure no other controllers are connected.
2. Open the game and go to controls
3. Rebind the S key 
4. Go to gallery

**Result expected:** Gallery works
**Result achieved:** Game freezes

### Examples
![image](https://user-images.githubusercontent.com/77382010/184359767-ba9a8957-dec0-4045-8c6a-185a32215509.png)

### Error Log
`ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00000] in <00000000000000000000000000000000>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <00000000000000000000000000000000>:0 
  at _0G.Legacy.UIMenu.Update () [0x00000] in <00000000000000000000000000000000>:0 `
(provided by one of the server members)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 11

**Comment by FullFrontalFrog** [comment]
Fix ready for v0.18.100!

**Comment by MagLjudik** [comment]
Bug is fixed in 0.18.200, gallery does not crash anymore.
