### ISSUE TITLE
Unable to bind same controls for different game categories

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#49]
### Summary
When using keybind customizer, it does not allow putting same key to multiple actions that, by default, are bound to one and same key. For example, rebinding X for something in-game makes it unusable in menu. 

### Consequences
Rebinding keys might lead to unexpected behaviour, like issue #48

### Steps to recreate
1. Go to Key bind settings
2. Try to rebind something to "confirmation" button.

**Result expected:** Player would be able to set same control for multiple actions that are not in the same category (like X in menu is confirmation, and in game it's jump)
**Result achieved:** Rebinding the key removes all it's uses.

### Examples
Default
![image](https://user-images.githubusercontent.com/77382010/184362451-8cdd8b34-65c8-4f49-af6e-6d1c77b64a79.png)

After rebinding of S
![image](https://user-images.githubusercontent.com/77382010/184362520-bd647ae6-0c6c-4525-974b-fb0dfb57d4a7.png)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 11

**Comment by FullFrontalFrog** [comment]
Fix ready for v0.18.100!

**Comment by MagLjudik** [comment]
Issue is solved, now that you can bind one key to multiple things. I apologize for late reply.
