### ISSUE TITLE
Hiroto Dojo: Buggy door

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#50]
### Summary
In August 2022 release, the new area in Hiroto Dojo was introduced. In the area, there's a locked door, which is a source to multiple bugs:

* Enemies can see Joe through the door
* Enemies and projectiles can hit Joe through the door.
* Joe can force-slide through it, thus even unlocking it and skipping part of the level (Hard to replicate)
* Some users have reported that Joe can get stuck when butt-slamming near the locked door or even fall out of bounds (hard to replicate)

### Consequences
Players might get out of bounds, soft-lock game or miss portions of level.

### Examples
![image](https://user-images.githubusercontent.com/77382010/185757416-803fcc22-7c7c-4cff-bb9a-0105fc1d190b.png)
Joe gets hit by bubbles through the door.
![image](https://user-images.githubusercontent.com/77382010/185757647-449f1cce-2840-4eea-ba70-f6bea37cbb77.png)
Joe stuck near the door

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic  settings, Windows 11

**Comment by FullFrontalFrog** [comment]
Some fixes will be ready next version. Let's revisit then.

**Comment by MagLjudik** [comment]
This bug seems to have been fixed in 0.18.200. However, Joe is still able to swoon Bax thruogh the door.

**Comment by FullFrontalFrog** [comment]
> This bug seems to have been fixed in 0.18.200. However, Joe is still able to swoon Bax thruogh the door.

Can you provide a video of how this looks?

I might have to defer this fix to a later time. I believe it's a general problem that needs to be addressed with new level design tools and/or enemy logic changes.

**Comment by MagLjudik** [comment]
Apparently Dropbox is not letting me upload any more videos in the issue folders, as for some reason all these issuses are taking space on my 2GB free storage and now it's full.

**Comment by FullFrontalFrog** [comment]
> Apparently Dropbox is not letting me upload any more videos in the issue folders, as for some reason all these issuses are taking space on my 2GB free storage and now it's full.

You may need to transfer ownership of the files to my account. Send me a DM on Discord and we can figure it out!

**Comment by MagLjudik** [comment]
I have uploaded the video to Folder T0050

**Comment by FullFrontalFrog** [comment]
Thanks! It's as I expected. I'm gonna spin off a new task for this (#54) and close the current issue.
