### ISSUE TITLE
Sliding while entering other level soft-locks controls

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#51]
### Summary 
From Discord user:
> Sliding while entering a teleport location (one of the shops in loof city for example) will make the player unable to move after teleporting

I wasn't able to replicate it, but it might have some relation to #6 

### Consequences
Game is soft-locked

### Steps to recreate
???

### Examples
None

### Error Log
Was not provided

### Configuration and system information
Was not provided

**Comment by FullFrontalFrog** [comment]
This issue is old and I'm not able to replicate this in the latest code. Closed.
