### ISSUE TITLE
Collision error in Hiroto Dojo east building

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#55]
### Summary
In east building, when entering from the roof, there's a chance to get stuck in the corner of the building. Only relaunching the level can fix it.

### Consequences
Player gets stuck

### Steps to recreate
1. Go to Hiroto dojo
2. Get to the roof of East building
3. Enter it from the right side (go left, that is)
4. Keep going until the corner. 

### Examples
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/77382010/209112289-2c468bfb-0b2e-49fc-913b-63cf1f19c8da.png">

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic settings, Windows 11

**Comment by FullFrontalFrog** [comment]
I was able to recreate this (though not consistently). There is in fact a tiny gap there between the wall and floor. I have sealed it off in 0.18.500. To be retested later.

**Comment by MagLjudik** [comment]
Fixed in 0.18.500
