### ISSUE TITLE
Mac build installation error

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#57]
### Summary
One of patrons has issues with mac build:
> something is up with the mac download, i keep getting "App is damaged and can’t be opened. You should move it to the Trash” error

### Consequences
Game cannot be started 

### Workaround
In terminal type
 ``xattr -cr <full path to the file>``

### Configuration and system information
Mac OS  Monterey, CPU/GPU M1 Pro

**Comment by FullFrontalFrog** [comment]
I am investigating additional solutions. In the meantime, please use the workaround listed above.

**Comment by FullFrontalFrog** [comment]
I've made an Apple silicon build for 0.19.000. Let's see if this fixes the issue.

**Comment by FullFrontalFrog** [comment]
@MagLjudik Do you happen to know which patron(s) had this issue and if the new version works for them? If not, just mark this as closed because I tested it myself and it works fine.

**Comment by MagLjudik** [comment]
Seems like issue was resolved before
