### ISSUE TITLE
Game stuck at loading screen when entering Ali's Surf Shack

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#61]
### Summary
A user has reported that they can't get into Surf Shack - the game gets stuck at loading screen.
I did not have this issue when I tested

### Consequences
Player can't access some content

### Error Log
[Player.log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/11115935/Player.3.log)
[Player-prev.log](https://github.com/FullFrontalFrog/OhSoHeroTracker/files/11115938/Player-prev.3.log)

**Comment by FullFrontalFrog** [comment]
I notice the errors in the logs and will take a closer look at my code.

**Comment by FullFrontalFrog** [comment]
I couldn't reproduce this either, but I added better error logging. We should check this out after next build.

**Comment by FullFrontalFrog** [comment]
This error happened in 0.19.000 due to null CharacterDossiers and null references in ObjectManager.RegisterCharacterAsync. This code was updated in later versions and no errors of this sort have been reported since, so I will mark this as closed and complete.
