### ISSUE TITLE
Autosave issues during location switch

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#63]
### Summary
Sometimes, when switching location, the game does not save it, and thus, if game over happens, player will restart at the start of previous location.

This can be fixed by, after switching location, moving slightly away from the entrance and then back to it, thus triggering autosave. However, if game over happens, you're still teleported to the beginning of the level rather than the entrance you entered through.

To trigger it, try switching locations and check if there's "yellow star" that confirms autosave. If there is, try to switch location again.

**Comment by FullFrontalFrog** [comment]
A fix has been made. This should be resolved next build!

**Comment by MagLjudik** [comment]
This one is fixed. See #64 for another teleporter-related issue.
