### ISSUE TITLE
Retry and Continue teleports you to the beginning of the level

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#64]
Oh So Hero: v. 0.19.100

Joe gets teleported to beginning of the level rather than last entrance he went through.
This happens when:
* Joe get's KO:d and player presses Retry
* When player exits the game and loads it

Not sure if it's a bug or feature. If latter, please close it.

**Comment by FullFrontalFrog** [comment]
Sounds like a bug to me. I'll check on this more a bit later. Thanks!

**Comment by FullFrontalFrog** [comment]
I have a fix ready for both Game Over Retry and save file loading. To be tested in 0.19.200!

**Comment by MagLjudik** [comment]
Issue seems to be gone in prerelease build
