### ISSUE TITLE
Stier's animation issue

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#65]
Oh So Hero! v.0.19.100

After Joe gets K.O:d and player presses Retry in Lood City, Stier's animation is frozen, but enemy still moves. It's fixed once distance is short enough for interaction.
This does not appear upon entering Lood City from other area.

Bug record: See T0065 on Issue Dropbox.

**Comment by FullFrontalFrog** [comment]
I have a fix ready for 0.19.200!

**Comment by MagLjudik** [comment]
Fixed in pre-release build
