### ISSUE TITLE
Hiroto Dojo eastern building camera issue

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#66]
Oh So Hero! v.0.19.100

Sometimes Joe can bounce too high to trigger camera switch to upper floor, which stays there until Joe gets new interaction or triggers another camera switch.

For demonstration of the bug, see T0066 on dropbox.

**Comment by MagLjudik** [comment]
To this I can also add the issue Spaghetfrog encountered on the roof of this building, in some cases when Joe butt-stomps it, camera goes to interior view. This one is fixed by pausing and unpausing the game.

**Comment by FullFrontalFrog** [comment]
Possible fix ready for upcoming 0.19.200 build.

**Comment by MagLjudik** [comment]
The camera seems to work just fine in eastern building. However, please check location around first Haya,  camera suddenly shifts slightly back at some point there.

**Comment by FullFrontalFrog** [comment]
> The camera seems to work just fine in eastern building. However, please check location around first Haya, camera suddenly shifts slightly back at some point there.

Follow up in #44

**Comment by MagLjudik** [comment]
Specifically this issue can be marked as closed, since the camera issue I mentioned in comment above is more related to a followup issue 44. Everything else is fine.
