### ISSUE TITLE
Amaru's Projectile Issues

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#69]
Amaru's projectile is a bit bugged. Here's what I found: 

1. Projectile does not move when Amaru is on a platform or other surface Joe can jump up through
2. Projectile moves fainted enemies and items on the ground (coins)

See T0069 on dropbox for demo.

**Comment by FullFrontalFrog** [comment]
I have a fix ready for 0.20.100.

ELABORATION
1. Issue 1 is resolved. The projectile will move on a jump through platform/surface.
2. Issue 2 is conditionally resolved. The projectile will not move fainted enemies. However, it may still move items on the ground such as coins. I've decided this is OK. Unity has a hard limit on collider layers, so I can't easily change this.

**Comment by MagLjudik** [comment]
Both issues are resolved as of 0.20.700. Amaru's projectile is functioning correctly and no longer collides with fained enemies. Did not collide with a coin on the ground either when I tested :)

**Comment by FullFrontalFrog** [comment]
Issue 69 closed. Nice~
