### ISSUE TITLE
Whitescreen bug

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#72]
Whitescreen bug happens if you push Confirm button before the white splashscreen starts fading. You can still get the game going and use controls, but won't see anything. This bug seems to be old, I saw it in Pre Edition II as well (however, since it has no splash screen on loading, whitescreen disappears once you enter the game) and is triggered whenever you enter title screen (both at start or after the game). 

This is mostly happening when you "rush press" the confirmation button, which might happen to some people like myself, who wanna get in game ASAP. 

For demo, Check T0072 on dropbox

**Comment by FullFrontalFrog** [comment]
I fixed a similar issue recently ([#1015](https://github.com/FullFrontalFrog/OhSoHero/issues/1015)). I'll try to have this one fixed by next public release.

**Comment by FullFrontalFrog** [comment]
Fix ready for 0.20.100!

**Comment by MagLjudik** [comment]
The Issue is fixed as of 0.20.700
