### ISSUE TITLE
Camera Tween Issues with Loading Confirmation Off

### ISSUE THREAD

**Issue by FullFrontalFrog** [FullFrontalFrog/OhSoHeroTracker#74]
0.19.200 Known Issues:

When Loading Confirmation is disabled, some scenes start with a camera tween to Joe from another position off screen.

_With confirmation off, some scenes load in with a weird camera tween (e.g. going from Southeast Beach to Treewish Forest)._

**Comment by FullFrontalFrog** [comment]
Fix ready for 0.19.300!

**Comment by MagLjudik** [comment]
Fixed
