### ISSUE TITLE
Haya’s Sexy Star taunt animation is missing

### ISSUE THREAD

**Issue by FullFrontalFrog** [FullFrontalFrog/OhSoHeroTracker#75]
0.19.200 Known Issues:

Haya’s Sexy Star taunt animation is missing. He is using his standard high throw animation instead. The proper animation will be added next build.

**Comment by FullFrontalFrog** [comment]
The animation is completed and ready for 0.19.300.

**Comment by MagLjudik** [comment]
Fixed
