### ISSUE TITLE
Haya's ninja star attacks glitch sometimes

### ISSUE THREAD

**Issue by FullFrontalFrog** [FullFrontalFrog/OhSoHeroTracker#76]
Haya's stars sometimes don't throw when they should (cooldown mismatch, perhaps), and they also disappear abruptly/arbitrarily.

**Comment by FullFrontalFrog** [comment]
I conflated two different issues because I mistook Haya's grab animation as a throwing animation.

1. When Joe is close to Haya, Haya attempts to grab, but he is slightly too far away to do this. I've made a fix for this in 0.19.300.

2. The disappearing of the stars is mostly a cosmetic issue. I don't think it warrants a ticket, so we can ignore for now.

**Comment by MagLjudik** [comment]
Issue with grab fixed
Please close if you think it doesn't need to be open anymore :)

**Comment by FullFrontalFrog** [comment]
This seems good now. Closing!
