### ISSUE TITLE
Awakened yellow star does not appear immediately upon meeting condition

### ISSUE THREAD

**Issue by FullFrontalFrog** [FullFrontalFrog/OhSoHeroTracker#77]
0.19.200 Known Issues:

The Awakened yellow star does not appear immediately when the Awakened condition is met (as it should). Currently it waits until the next available move to be evaluated.

Conditions:
- Haya: LP >= 50%.
- Bax: HP <= 50%.

**Comment by FullFrontalFrog** [comment]
This should have already been fixed with my Enemy AI overhaul work done at the end of July 2024. Local testing and code examination seems to confirm this. Please test one more time on 0.20.701 or later and get this closed if it's good.

**Comment by MagLjudik** [comment]
Issue is fixed as of 0.20.800
