### ISSUE TITLE
More camera & enemy activation bugs

### ISSUE THREAD

**Issue by FullFrontalFrog** [FullFrontalFrog/OhSoHeroTracker#78]
0.19.200 Known Issues:

Some areas have new camera bugs and new enemy activation bugs introduced as a result of ongoing development to level design code.

- [x] _Camera bug in lower-right room in Brask's Jungle._
- [x] _Bax in east building of Hiroto Dojo shooting bubbles through a solid door._

**Comment by FullFrontalFrog** [comment]
Fix for Brask's Jungle in 0.19.300!

Unable to replicate Bax issue. Please ignore.

**Comment by MagLjudik** [comment]
Fixed
