### ISSUE TITLE
Signal and Puca do not attack

### ISSUE THREAD

**Issue by FullFrontalFrog** [FullFrontalFrog/OhSoHeroTracker#79]
Reported by R.J.
> Hello the build works great but I found another bug with this update. It looks like all the Signel Characters never attack you. 

Could be related to level room enemy activation (#78) or possibly AI.

_We need to make sure we do a full play-through of the game and check all enemy attacks/animations when testing for next build._

**Comment by MagLjudik** [comment]
Someone reported similar problems with Puca. I'll play through ASAP and will expand on this

**Comment by MagLjudik** [comment]
Here's my observations:

Puca: **Does not attack or grab**, unless Joe is in 100% lust state or KO:ed. Even then, after the deed is done, they return to this behavior. Attacking or lusting them does not help. It just floats around Joe.
Signal: Same as Puca, except he doesn't even move if Joe's near him. However, once Joe moves a certain distance away from Signal, the monkey starts following him, until reached a specific distance. 

No other enemies have this behavior.

**Comment by FullFrontalFrog** [comment]
Fix for Signal and Puca in 0.19.300. There was an obscure syntax error in a recent refactoring of AI randomization which prevented some of their attack subroutines from executing. It's fixed!

**Comment by MagLjudik** [comment]
Fixed
