### ISSUE TITLE
NPC dialog state reset

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#8]
### Summary
Once you leave location with an interactable NPC (e.g. Ket or Brask), their dialog and "heart" status get reset to "zero", as in, as Joe never spoke to them before. Same thing occurs when player exits the game and returns to it. This reset issue also affects the ability to quickly skip the dialog, which stays enabled only until player leaves the location.

### Consequences
Player has to go through the same dialogs many times in order to have "some fun" with characters, which might be annoying.

### Steps to recreate
1. Enter location with interactable character (Brask's Palace for example)
2. Find the character and talk with them. 
3. Leave the location or exit the game
4. Return to the same location or load the state again
5. Find and talk with the character again.

**Result expected:** Skippable dialogs or lack of those. 
**Result achieved:** Same dialog appears as if Joe and character didn't meet before at that spot. 

### Examples
See video [here](https://www.dropbox.com/s/o8mtqdyxdv3sf5p/Oh%20So%20Hero%21%202021-01-15%2015-48-51.mp4?dl=0) (Takes Brask as example)

### Configuration and system information
Desktop PC, Ryzen 7 2700X, 32GB RAM, nVidia GTX 1070Ti, 2560x1440, Fantastic settings, Windows 10.

**Comment by MagLjudik** [comment]
This is not a migrated issue, I noticed it while testing one of the issues in spreadsheet (which I decided to not migrate, because when I reported it before, I didn't think that unexitable dialog choices, aka "you have to choose something, no going back" might be a game design decision in some spots).

**Comment by FullFrontalFrog** [comment]
Unexitable dialog choices is common in many games. Not to say we will keep it this way, but we have no plans to change it at this time.

As for the state of the NPCs, this is something I will address. They should remember the conversations they had, and in due time they will.

**Comment by FullFrontalFrog** [comment]
This seems like two issues in one. Please retest the NPC dialog state because that should have been addressed in a previous update. If you would like to create a separate issue for the dialogue choices, we can review that later. Thanks!

**Comment by MagLjudik** [comment]
Issue fixed
